
service: landing-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: contact
          method: post
